from filmconnect import * 
from readfilms import *
import time

#subroutine/function
def insertfilms():
    #create a list
    tblfilms = []

    #ask user for the values to be entered in the songs table
    #filmID = autogenerated
    title = input("\nEnter film Title: ")
    yearReleased = input("\nEnter the Film Year Released: ")
    rating = input("\nEnter the Film Rating: ")
    duration = input("\nEnter the Film Duration: ")
    genre = input("\nEnter the Film Genre: ")

    tblfilms.append(title)
    tblfilms.append(yearReleased)
    tblfilms.append(rating)
    tblfilms.append(duration)
    tblfilms.append(genre)

    cursor.execute("\ninsert into tblfilms(Title, YearReleased, Rating, Duration, Genre) values(?,?,?,?,?)",tblfilms)
    conn.commit()
    print(f"\n{title} inserted into table films")
    time.sleep(4)

    # to read from database
    readfilms()


if __name__ =="__main__":
    insertfilms()









