insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('How to Eat Your Watermelon in White Company (and Enjoy It)', 2020, 10, '80 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Source, The', 1995, 5, '80 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('No Flesh Shall Be Spared', 2021, 7, '80 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Up at the Villa', 2010, 2, '105 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Madonna: Truth or Dare', 2005, 8, '100 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Cat o'' Nine Tails, The (Gatto a nove code, Il)', 2000, 5, '125 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Subspecies IV: Bloodstorm', 2005, 8, '105 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Gloomy Sunday (Ein Lied von Liebe und Tod)', 1990, 2, '90 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Cube of Sugar, A (Ye Habe Ghand)', 1990, 10, '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Peck on the Cheek, A (Kannathil Muthamittal)', 2010, 9, '115 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Mr. Jones', 1995, 10, '110 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Lightning in a Bottle', 2015, 1, '100 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Métamorphose des cloportes, La', 1995, 5, '95 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Chapiteau-show (Shapito-shou)', 2015, 1, '135 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Iceman Tapes: Conversations with a Killer, The', 2015, 6, '90 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Windtalkers', 2021, 5, '80 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Love, Rosie', 2021, 1, '120 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Grim Reaper', 2015, 9, '115 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Where Is the Friend''s Home? (Where Is My Friend''s House?) (Khane-ye doust kodjast?)', 2005, 4, '80 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Like You Know It All (Jal aljido mothamyeonseo)', 2000, 9, '110 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('This Is the End', 2000, 7.2, '135 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Turning Point, The', 2005, 2, '95 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Viva Knievel!', 1995, 10, '90 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Destricted', 2010, 9, '95 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Law of Enclosures, The', 2021, 5, '100 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Vice', 2000, 8, '120 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Rules of Attraction, The', 1995, 2, '80 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Innocent, The (Innocente, L'')', 1990, 7.2, '110 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Whisperer in Darkness', 2010, 8, '105 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pretty Bird', 1990, 2, '90 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('With Friends Like These...', 2020, 5, '100 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Left Behind: World at War', 2000, 6, '135 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Spanish Earth, The', 2021, 3, '115 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Zulu', 2010, 8, '115 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Primus Hallucino-Genetics Live 2004', 2021, 7.2, '105 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('There''s No Business Like Show Business', 2020, 7, '115 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ambushers, The', 1995, 3, '135 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bride of the Monster', 2005, 10, '135 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Chinese Zodiac (Armour of God III) (CZ12)', 2020, 6, '120 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Sketches of Frank Gehry', 2015, 8, '95 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Free Will, The (Freie Wille, Der)', 2010, 7.2, '120 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Little Man', 2010, 3, '95 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dr. No', 1995, 5, '100 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Song of the Little Road (Pather Panchali)', 1995, 6, '95 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Chamber of Death (Chambre des morts, La)', 2000, 8, '110 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('First Man, The (Le Premier Homme)', 2000, 2, '90 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Beach Red', 2000, 10, '135 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bloody New Year', 2005, 10, '115 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Freshman, The', 2020, 7, '105 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Unfinished Song (Song for Marion)', 1990, 4, '135 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Viy or Spirit of Evil (Viy)', 2020, 5, '120 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ceremony', 2000, 2, '90 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pie in the Sky', 2005, 2, '90 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Son of the Mask', 2015, 4, '115 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Enlighten Up!', 1990, 9, '110 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Perfume of the Lady in Black, The (Il profumo della signora in nero)', 1995, 2, '80 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Touch', 1990, 7.2, '110 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('If God Is Willing and da Creek Don''t Rise', 2005, 9, '90 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Surprise', 2010, 4, '105 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Hello Mary Lou: Prom Night II', 2000, 10, '115 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Take the Trash', 2020, 7.2, '115 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Tale of Winter, A (a.k.a. A Winter''s Tale) (Conte d''hiver)', 2010, 5, '135 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Versus', 2005, 6, '135 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bed & Breakfast: Love is a Happy Accident (Bed & Breakfast)', 1990, 5, '120 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Labor Pains', 2021, 5, '125 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Genius Within: The Inner Life of Glenn Gould', 1995, 3, '90 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Promise Her Anything', 1990, 7, '95 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Twilight', 1990, 1, '115 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Helter Skelter', 2005, 6, '105 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('White Hell of Pitz Palu, The (Die weiße Hölle vom Piz Palü) ', 2000, 7, '135 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Young and the Dead, The', 1995, 10, '105 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Top Five', 2000, 9, '90 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Flying Down to Rio', 2000, 3, '135 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('I Am Bruce Lee', 2021, 2, '95 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Jungle Man-Eaters', 2021, 1, '90 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Vinyan', 2000, 2, '125 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('In Search of a Midnight Kiss', 2000, 6, '125 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Clerks', 2020, 9, '105 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Company You Keep, The', 1995, 5, '115 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dennis the Menace', 2010, 7.2, '135 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bullitt', 2015, 5, '135 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Risky Business', 2010, 8, '115 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Melody', 2021, 10, '135 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('With Love... from the Age of Reason', 1995, 5, '115 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Beaver Trilogy Part IV', 2000, 5, '115 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Mildred Pierce', 2000, 1, '110 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('To the Wonder', 2000, 3, '100 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Collapse', 2010, 8, '95 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Captive, The (La captive)', 2010, 1, '120 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Closing the Ring', 2020, 9, '90 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('War of the Shaolin Temple (Shao Lin shi san gun seng)', 2005, 4, '105 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Amreeka', 2020, 2, '125 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Out-of-Towners, The', 2010, 3, '95 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Great Balls of Fire!', 2000, 3, '100 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dodgeball: A True Underdog Story', 2015, 9, '125 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('I Love You Again', 2021, 4, '125 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pulse (Kairo)', 2005, 9, '95 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Million Dollar Legs', 2000, 4, '105 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Culloden (The Battle of Culloden)', 2015, 10, '100 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Frankenstein Conquers the World', 2010, 3, '80 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Counterfeiters, The (Le cave se rebiffe)', 2015, 7.2, '110 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Objectified', 2021, 3, '125 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Black Dragons', 2005, 7.2, '90 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ordinary Decent Criminal', 2005, 7, '115 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('All or Nothing', 2021, 2, '90 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Naked Weapon (Chek law dak gung)', 1995, 4, '115 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Front, The', 1990, 7, '105 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Woman in Black, The', 2020, 6, '135 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Skipped Parts', 1990, 8, '115 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Lost Thing, The', 1995, 6, '100 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Colossus: The Forbin Project', 1990, 10, '80 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Planet of the Future, The', 2010, 4, '115 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Avenging Conscience, The', 1990, 7.2, '105 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Capricious Summer (Rozmarné léto)', 2010, 10, '90 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dark Island', 2021, 1, '115 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('In the House', 1990, 8, '110 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Matriarch, The (Lieksa!)', 2015, 5, '110 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Breaking Point, The', 2010, 8, '110 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Couch Trip, The', 1995, 4, '125 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Went the Day Well?', 1995, 2, '105 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Balls Out: Gary the Tennis Coach', 1995, 4, '120 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Queen Kelly', 1995, 1, '105 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Results', 2021, 1, '80 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Greystoke: The Legend of Tarzan, Lord of the Apes', 2021, 8, '125 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Management', 2005, 7, '95 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Hijack That Went South, The (Kaappari)', 2021, 4, '105 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Jason''s Lyric', 1995, 7.2, '125 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Richard III', 2015, 6, '125 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Inquisitor, The (a.k.a. Under Suspicion) (Garde à vue)', 2020, 1, '115 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Body/Cialo', 2021, 8, '115 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Yesterday', 2005, 3, '100 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Once Upon a Crime...', 1990, 2, '110 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Blazing Saddles', 2015, 1, '120 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Spriggan (Supurigan)', 2010, 7.2, '100 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Stitches', 2000, 7, '105 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('La Rabbia', 2005, 7.2, '105 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Don''t Change Your Husband', 2005, 9, '90 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('So Fine', 2005, 9, '115 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ranma ½: Nihao My Concubine (Ranma ½: Kessen Tôgenkyô! Hanayome o torimodose!!)', 1995, 3, '125 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Notorious Bettie Page, The', 2021, 10, '115 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('A Chinese in a Coma', 1990, 8, '125 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Stakeout', 2000, 5, '90 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Paranoia', 2000, 6, '110 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('On the Ice', 2005, 1, '80 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Act of Violence', 2015, 9, '125 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Phantom', 2020, 5, '125 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('After Sex', 2000, 8, '105 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Heart of a Lion (Leijonasydän)', 2000, 8, '110 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Must Love Dogs', 2021, 10, '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Blood for Dracula (Andy Warhol''s Dracula)', 2020, 5, '110 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Good Wife, The', 2020, 3, '120 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Flood', 2000, 4, '115 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dry Summer (Susuz yaz) (Reflections)', 2010, 7, '115 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dog Soldiers', 1990, 8, '115 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('We Are the Best! (Vi är bäst!)', 1990, 1, '115 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Enemy Within, The (O ehthros mou)', 2010, 2, '105 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Host, The (Gwoemul)', 2000, 1, '110 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('High on Crack Street: Lost Lives in Lowell', 2010, 7.2, '80 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Zodiac', 1995, 5, '105 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Sweeney Todd: The Demon Barber of Fleet Street', 1995, 7.2, '95 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('P2', 2010, 9, '90 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Redemption: For Robbing the Dead', 1990, 4, '115 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('I Know That Voice', 2015, 1, '95 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Mark of Cain', 2010, 7.2, '90 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Han Gong-ju', 2005, 6, '90 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Igor', 2005, 10, '105 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bamboozled', 2000, 7.2, '115 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Sexual Dependency (Dependencia sexual)', 2021, 7.2, '90 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('27 Missing Kisses', 1990, 10, '125 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Shakespeare High', 2020, 3, '125 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Phoenix', 2005, 1, '95 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Toy Story That Time Forgot', 2010, 2, '115 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Eastern Plays', 2000, 2, '105 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('In a Town This Size', 2021, 8, '125 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Pushing Hands (Tui shou)', 2020, 4, '125 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('NeverEnding Story III, The', 2021, 2, '90 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Guy and Madeline on a Park Bench', 2010, 7, '135 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Désiré', 1990, 1, '115 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Everybody''s All-American', 2000, 1, '110 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Afghan Luke', 2010, 7, '80 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Mr. Hobbs Takes a Vacation', 1995, 10, '105 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('À propos de Nice', 1995, 7, '125 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bag of Bones', 2015, 7.2, '110 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Last Farm', 2020, 10, '120 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Meet the Applegates', 2021, 5, '100 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Black Rainbow', 2010, 9, '135 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Message to Love: The Isle of Wight Festival', 1990, 7, '95 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Valley of the Dragons', 2000, 7.2, '120 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ghosts (Gespenster)', 2021, 8, '90 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('No Time for Nuts', 2020, 6, '135 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Summer and Smoke', 1990, 10, '125 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Talaash', 2020, 9, '110 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('This Ain''t California', 2020, 10, '105 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Crime of Father Amaro, The (Crimen del padre Amaro, El)', 1990, 5, '115 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Inner Circle', 1990, 1, '120 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('To Live (Huozhe)', 2021, 9, '80 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Natural Love', 2021, 10, '115 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Story of Louis Pasteur, The', 1995, 8, '125 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Four-Faced Liar, The', 2010, 6, '110 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Brother from Another Planet, The', 1990, 2, '110 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Let''s Get Those English Girls', 2010, 4, '95 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('You Don''t Mess with the Zohan', 2020, 5, '105 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ghost Machine', 1995, 1, '90 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Adventures in Babysitting', 2015, 3, '105 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Circumstance', 1995, 3, '120 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dragonwyck', 2015, 7.2, '125 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Entertaining Angels: The Dorothy Day Story', 2015, 7.2, '80 minutes', 'Action');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Kind Hearts and Coronets', 1995, 8, '115 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('On the Edge (Hak bak do)', 2021, 10, '90 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('As Good as Dead', 2020, 3, '125 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Prince of Tides, The', 2010, 10, '125 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('American Pie Presents Beta House (American Pie 6: Beta House)', 1995, 3, '115 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Don Q Son of Zorro', 2000, 10, '100 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Marie and Bruce', 2000, 8, '80 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ned Kelly', 1990, 6, '125 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Twelve', 1990, 5, '135 minutes', 'Mystery');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dernier Combat, Le (Last Battle, The)', 1995, 9, '135 minutes', 'Horror');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Ricky Gervais Live 3: Fame', 1995, 7.2, '110 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Four Rooms', 2015, 6, '125 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Khumba', 2015, 10, '90 minutes', 'Crime');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Tales of the Grim Sleeper', 2005, 3, '90 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('TMNT (Teenage Mutant Ninja Turtles)', 2005, 4, '80 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Lucky', 1995, 2, '105 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Theory of Flight, The', 2010, 2, '95 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Babylon 5', 2005, 1, '100 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Comedy, The', 2005, 1, '125 minutes', 'Western');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('No Blade of Grass', 2015, 5, '100 minutes', 'Thriller');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Dog Park', 2010, 1, '105 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Iran Job, The', 2015, 6, '110 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('War Dance', 2010, 7.2, '105 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Aberdeen', 2000, 3, '110 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Monsieur Vincent', 1995, 7, '120 minutes', 'Drama');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Army of Shadows (L''armée des ombres)', 1990, 2, '115 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Griffin and Phoenix', 1990, 7, '80 minutes', 'Musical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Here Comes the Boom', 2000, 9, '100 minutes', 'Comedy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Three Marias, The (Três Marias, As)', 2010, 9, '115 minutes', 'Animation');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Loft', 1995, 2, '100 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Red Chapel, The (Røde kapel, Det)', 2021, 7.2, '95 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Mr. Belvedere Goes to College', 2015, 9, '125 minutes', 'War');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Digimon: The Movie', 1995, 10, '105 minutes', 'Science Fiction');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Matriarch, The (Lieksa!)', 2010, 6, '125 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('The Mule', 2005, 5, '120 minutes', 'Sports');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Homework', 2005, 9, '100 minutes', 'Historical');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Burning Palms', 1995, 6, '95 minutes', 'Adventure');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Color Me Blood Red', 2000, 2, '105 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('My Little Pony: Equestria Girls', 2015, 10, '125 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Italian, The (Italianetz)', 2020, 1, '95 minutes', 'Documentary');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Midnight in the Garden of Good and Evil', 1990, 7, '110 minutes', 'Fantasy');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Spring Subway', 2015, 1, '95 minutes', 'Romance');
insert into tblfilms (Title, YearReleased, Rating, Duration, Genre) values ('Bohemian Life, The (La vie de bohème)', 2010, 5, '105 minutes', 'Animation');
